# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      BRANCH_NAME:
        description: 'New Branch Name'
        default: 'release'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: master
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Confirm new branch doesn't exist
      shell: bash
      run: |
        giturl=$(git ls-remote --get-url)
        echo $giturl
        git ls-remote --exit-code --heads \
        $giturl ${{ inputs.BRANCH_NAME }} 2> /dev/null
        echo "here1"
        EXIT_CODE=$?
        echo "here2"
        echo $EXIT_CODE
        if [[ $EXIT_CODE == '0' ]]; then
          echo "Git branch '${{ inputs.BRANCH_NAME }}' exists in the remote repository"
        elif [[ $EXIT_CODE == '2' ]]; then
          echo "Git branch '${{ inputs.BRANCH_NAME }}' does not exist in the remote repository"
        fi

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.email github-actions@github.com
        git config --global user.name github-actions

    - name: Create new branch
      shell: bash
      run: |
        git status
        git checkout -b ${{ inputs.BRANCH_NAME }}
        git push --set-upstream origin ${{ inputs.BRANCH_NAME }}
